### ISSUE TITLE
Requesting to implementing product tracking with time lines

### ISSUE THREAD

**Issue by kk8152** [kk8825/Flipart-Devlopment#5]
Respected kk8825,
                          Your doing great. my request is to implement the product tracking with exact times. kindly review and implements or adding the new enhancement. thanking you.

**Comment by kk8825** [comment]
Respected kk8152,
                        Your enhancement idea was amazing. we will adding the your idea of feature in future, keep contributing us. thanking you.

**Comment by kk8825** [comment]
Dear kk8152 thanks for your valuable suggestion. you are make our product great.
